<html>
    <body>
        <div>
            <ul>
                <li>a1</li>
                <li>b2</li>
                <li>c3</li>
                <li>d4</li>
            </ul>
        </div>
    </body>
</html>